-- =============================================================================
-- Seed: ESSLCE Biology 2013 (2020-2021 G.C.) Curriculum Classification Mappings
-- Mapped to the New Ethiopian Curriculum (Grades 9-12)
-- Structured for Multi-Subject & Multi-Year Customization
-- =============================================================================

-- 1. Ensure curriculum framework exists
INSERT INTO public.curriculum_frameworks (id, name_en, name_am, start_year, is_active) VALUES ('new_curriculum_2023', 'New Ethiopian Secondary Curriculum (Grades 9-12)', 'አዲሱ የኢትዮጵያ ሁለተኛ ደረጃ ሥርዓተ ትምህርት (9-12ኛ ክፍል)', 2023, TRUE) ON CONFLICT (id) DO NOTHING;

-- 2. Insert mappings and update questions
-- Question 1: Grade 12, Unit bio_g12_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_001', 'biology_g12', 2013, 'new_curriculum_2023', 12, 'bio_g12_u2', 1, 'Evolution & Animal Behavior (Ethology)', 'ዝግመተ-ለውጥ እና የእንስሳት ባህሪ', 'comprehension') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=12, curriculum_unit_id='bio_g12_u2' WHERE id='q_bio_2013_001';

-- Question 2: Grade 12, Unit bio_g12_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_002', 'biology_g12', 2013, 'new_curriculum_2023', 12, 'bio_g12_u2', 2, 'Evolution & Animal Behavior (Ethology)', 'ዝግመተ-ለውጥ እና የእንስሳት ባህሪ', 'knowledge') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=12, curriculum_unit_id='bio_g12_u2' WHERE id='q_bio_2013_002';

-- Question 3: Grade 12, Unit bio_g12_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_003', 'biology_g12', 2013, 'new_curriculum_2023', 12, 'bio_g12_u2', 3, 'Evolution & Animal Behavior (Ethology)', 'ዝግመተ-ለውጥ እና የእንስሳት ባህሪ', 'application') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=12, curriculum_unit_id='bio_g12_u2' WHERE id='q_bio_2013_003';

-- Question 4: Grade 12, Unit bio_g12_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_004', 'biology_g12', 2013, 'new_curriculum_2023', 12, 'bio_g12_u2', 4, 'Evolution & Animal Behavior (Ethology)', 'ዝግመተ-ለውጥ እና የእንስሳት ባህሪ', 'comprehension') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=12, curriculum_unit_id='bio_g12_u2' WHERE id='q_bio_2013_004';

-- Question 5: Grade 12, Unit bio_g12_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_005', 'biology_g12', 2013, 'new_curriculum_2023', 12, 'bio_g12_u2', 5, 'Evolution & Animal Behavior (Ethology)', 'ዝግመተ-ለውጥ እና የእንስሳት ባህሪ', 'application') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=12, curriculum_unit_id='bio_g12_u2' WHERE id='q_bio_2013_005';

-- Question 6: Grade 12, Unit bio_g12_u1
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_006', 'biology_g12', 2013, 'new_curriculum_2023', 12, 'bio_g12_u1', 6, 'Microorganisms and Human Health', 'ደቂቅ አካላትና የሰው ጤና', 'knowledge') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=12, curriculum_unit_id='bio_g12_u1' WHERE id='q_bio_2013_006';

-- Question 7: Grade 12, Unit bio_g12_u1
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_007', 'biology_g12', 2013, 'new_curriculum_2023', 12, 'bio_g12_u1', 7, 'Microorganisms and Human Health', 'ደቂቅ አካላትና የሰው ጤና', 'comprehension') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=12, curriculum_unit_id='bio_g12_u1' WHERE id='q_bio_2013_007';

-- Question 8: Grade 12, Unit bio_g12_u3
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_008', 'biology_g12', 2013, 'new_curriculum_2023', 12, 'bio_g12_u3', 8, 'Applied Biotechnology & Genetic Engineering', 'የተግባራዊ ባዮቴክኖሎጂና ጄኔቲክ ምህንድስና', 'application') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=12, curriculum_unit_id='bio_g12_u3' WHERE id='q_bio_2013_008';

-- Question 9: Grade 12, Unit bio_g12_u1
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_009', 'biology_g12', 2013, 'new_curriculum_2023', 12, 'bio_g12_u1', 9, 'Microorganisms and Human Health', 'ደቂቅ አካላትና የሰው ጤና', 'comprehension') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=12, curriculum_unit_id='bio_g12_u1' WHERE id='q_bio_2013_009';

-- Question 10: Grade 9, Unit bio_g9_u5
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_010', 'biology_g12', 2013, 'new_curriculum_2023', 9, 'bio_g9_u5', 10, 'Human Health, Nutrition & Infectious Diseases', 'የሰው ጤና፣ አመጋገብ እና ተላላፊ በሽታዎች', 'analysis') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=9, curriculum_unit_id='bio_g9_u5' WHERE id='q_bio_2013_010';

-- Question 11: Grade 12, Unit bio_g12_u1
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_011', 'biology_g12', 2013, 'new_curriculum_2023', 12, 'bio_g12_u1', 11, 'Microorganisms and Human Health', 'ደቂቅ አካላትና የሰው ጤና', 'application') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=12, curriculum_unit_id='bio_g12_u1' WHERE id='q_bio_2013_011';

-- Question 12: Grade 9, Unit bio_g9_u5
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_012', 'biology_g12', 2013, 'new_curriculum_2023', 9, 'bio_g9_u5', 12, 'Human Health, Nutrition & Infectious Diseases', 'የሰው ጤና፣ አመጋገብ እና ተላላፊ በሽታዎች', 'comprehension') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=9, curriculum_unit_id='bio_g9_u5' WHERE id='q_bio_2013_012';

-- Question 13: Grade 12, Unit bio_g12_u1
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_013', 'biology_g12', 2013, 'new_curriculum_2023', 12, 'bio_g12_u1', 13, 'Microorganisms and Human Health', 'ደቂቅ አካላትና የሰው ጤና', 'knowledge') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=12, curriculum_unit_id='bio_g12_u1' WHERE id='q_bio_2013_013';

-- Question 14: Grade 12, Unit bio_g12_u1
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_014', 'biology_g12', 2013, 'new_curriculum_2023', 12, 'bio_g12_u1', 14, 'Microorganisms and Human Health', 'ደቂቅ አካላትና የሰው ጤና', 'analysis') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=12, curriculum_unit_id='bio_g12_u1' WHERE id='q_bio_2013_014';

-- Question 15: Grade 9, Unit bio_g9_u5
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_015', 'biology_g12', 2013, 'new_curriculum_2023', 9, 'bio_g9_u5', 15, 'Human Health, Nutrition & Infectious Diseases', 'የሰው ጤና፣ አመጋገብ እና ተላላፊ በሽታዎች', 'application') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=9, curriculum_unit_id='bio_g9_u5' WHERE id='q_bio_2013_015';

-- Question 16: Grade 11, Unit bio_g11_u4
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_016', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u4', 16, 'Energy Transformation: Photosynthesis & Respiration', 'የሃይል ልውውጥ፡ ፎቶሲንተሲስና ሴሉላር አተነፋፈስ', 'knowledge') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u4' WHERE id='q_bio_2013_016';

-- Question 17: Grade 11, Unit bio_g11_u4
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_017', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u4', 17, 'Energy Transformation: Photosynthesis & Respiration', 'የሃይል ልውውጥ፡ ፎቶሲንተሲስና ሴሉላር አተነፋፈስ', 'application') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u4' WHERE id='q_bio_2013_017';

-- Question 18: Grade 11, Unit bio_g11_u4
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_018', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u4', 18, 'Energy Transformation: Photosynthesis & Respiration', 'የሃይል ልውውጥ፡ ፎቶሲንተሲስና ሴሉላር አተነፋፈስ', 'comprehension') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u4' WHERE id='q_bio_2013_018';

-- Question 19: Grade 11, Unit bio_g11_u4
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_019', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u4', 19, 'Energy Transformation: Photosynthesis & Respiration', 'የሃይል ልውውጥ፡ ፎቶሲንተሲስና ሴሉላር አተነፋፈስ', 'comprehension') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u4' WHERE id='q_bio_2013_019';

-- Question 20: Grade 11, Unit bio_g11_u4
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_020', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u4', 20, 'Energy Transformation: Photosynthesis & Respiration', 'የሃይል ልውውጥ፡ ፎቶሲንተሲስና ሴሉላር አተነፋፈስ', 'application') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u4' WHERE id='q_bio_2013_020';

-- Question 21: Grade 11, Unit bio_g11_u5
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_021', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u5', 21, 'Molecular Genetics & Protein Synthesis', 'ሞለኪዩላር ጄኔቲክስ እና የፕሮቲን ቅንብር', 'analysis') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u5' WHERE id='q_bio_2013_021';

-- Question 22: Grade 11, Unit bio_g11_u5
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_022', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u5', 22, 'Molecular Genetics & Protein Synthesis', 'ሞለኪዩላር ጄኔቲክስ እና የፕሮቲን ቅንብር', 'knowledge') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u5' WHERE id='q_bio_2013_022';

-- Question 23: Grade 12, Unit bio_g12_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_023', 'biology_g12', 2013, 'new_curriculum_2023', 12, 'bio_g12_u2', 23, 'Evolution & Animal Behavior (Ethology)', 'ዝግመተ-ለውጥ እና የእንስሳት ባህሪ', 'knowledge') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=12, curriculum_unit_id='bio_g12_u2' WHERE id='q_bio_2013_023';

-- Question 24: Grade 12, Unit bio_g12_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_024', 'biology_g12', 2013, 'new_curriculum_2023', 12, 'bio_g12_u2', 24, 'Evolution & Animal Behavior (Ethology)', 'ዝግመተ-ለውጥ እና የእንስሳት ባህሪ', 'comprehension') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=12, curriculum_unit_id='bio_g12_u2' WHERE id='q_bio_2013_024';

-- Question 25: Grade 12, Unit bio_g12_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_025', 'biology_g12', 2013, 'new_curriculum_2023', 12, 'bio_g12_u2', 25, 'Evolution & Animal Behavior (Ethology)', 'ዝግመተ-ለውጥ እና የእንስሳት ባህሪ', 'comprehension') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=12, curriculum_unit_id='bio_g12_u2' WHERE id='q_bio_2013_025';

-- Question 26: Grade 12, Unit bio_g12_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_026', 'biology_g12', 2013, 'new_curriculum_2023', 12, 'bio_g12_u2', 26, 'Evolution & Animal Behavior (Ethology)', 'ዝግመተ-ለውጥ እና የእንስሳት ባህሪ', 'application') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=12, curriculum_unit_id='bio_g12_u2' WHERE id='q_bio_2013_026';

-- Question 27: Grade 12, Unit bio_g12_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_027', 'biology_g12', 2013, 'new_curriculum_2023', 12, 'bio_g12_u2', 27, 'Evolution & Animal Behavior (Ethology)', 'ዝግመተ-ለውጥ እና የእንስሳት ባህሪ', 'comprehension') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=12, curriculum_unit_id='bio_g12_u2' WHERE id='q_bio_2013_027';

-- Question 28: Grade 12, Unit bio_g12_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_028', 'biology_g12', 2013, 'new_curriculum_2023', 12, 'bio_g12_u2', 28, 'Evolution & Animal Behavior (Ethology)', 'ዝግመተ-ለውጥ እና የእንስሳት ባህሪ', 'application') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=12, curriculum_unit_id='bio_g12_u2' WHERE id='q_bio_2013_028';

-- Question 29: Grade 12, Unit bio_g12_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_029', 'biology_g12', 2013, 'new_curriculum_2023', 12, 'bio_g12_u2', 29, 'Evolution & Animal Behavior (Ethology)', 'ዝግመተ-ለውጥ እና የእንስሳት ባህሪ', 'comprehension') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=12, curriculum_unit_id='bio_g12_u2' WHERE id='q_bio_2013_029';

-- Question 30: Grade 12, Unit bio_g12_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_030', 'biology_g12', 2013, 'new_curriculum_2023', 12, 'bio_g12_u2', 30, 'Evolution & Animal Behavior (Ethology)', 'ዝግመተ-ለውጥ እና የእንስሳት ባህሪ', 'application') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=12, curriculum_unit_id='bio_g12_u2' WHERE id='q_bio_2013_030';

-- Question 31: Grade 12, Unit bio_g12_u4
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_031', 'biology_g12', 2013, 'new_curriculum_2023', 12, 'bio_g12_u4', 31, 'Population Ecology, Biomes & Environment', 'የህዝብ ብዛት ኢኮሎጂ፣ ባዮሞችና አካባቢ', 'knowledge') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=12, curriculum_unit_id='bio_g12_u4' WHERE id='q_bio_2013_031';

-- Question 32: Grade 12, Unit bio_g12_u4
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_032', 'biology_g12', 2013, 'new_curriculum_2023', 12, 'bio_g12_u4', 32, 'Population Ecology, Biomes & Environment', 'የህዝብ ብዛት ኢኮሎጂ፣ ባዮሞችና አካባቢ', 'analysis') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=12, curriculum_unit_id='bio_g12_u4' WHERE id='q_bio_2013_032';

-- Question 33: Grade 10, Unit bio_g10_u5
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_033', 'biology_g12', 2013, 'new_curriculum_2023', 10, 'bio_g10_u5', 33, 'Conservation of Natural Resources', 'የተፈጥሮ ሀብት ጥበቃ', 'comprehension') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=10, curriculum_unit_id='bio_g10_u5' WHERE id='q_bio_2013_033';

-- Question 34: Grade 9, Unit bio_g9_u6
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_034', 'biology_g12', 2013, 'new_curriculum_2023', 9, 'bio_g9_u6', 34, 'Ecology & Environmental Conservation', 'ኢኮሎጂ እና የአካባቢ ጥበቃ', 'application') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=9, curriculum_unit_id='bio_g9_u6' WHERE id='q_bio_2013_034';

-- Question 35: Grade 12, Unit bio_g12_u4
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_035', 'biology_g12', 2013, 'new_curriculum_2023', 12, 'bio_g12_u4', 35, 'Population Ecology, Biomes & Environment', 'የህዝብ ብዛት ኢኮሎጂ፣ ባዮሞችና አካባቢ', 'comprehension') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=12, curriculum_unit_id='bio_g12_u4' WHERE id='q_bio_2013_035';

-- Question 36: Grade 12, Unit bio_g12_u1
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_036', 'biology_g12', 2013, 'new_curriculum_2023', 12, 'bio_g12_u1', 36, 'Microorganisms and Human Health', 'ደቂቅ አካላትና የሰው ጤና', 'analysis') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=12, curriculum_unit_id='bio_g12_u1' WHERE id='q_bio_2013_036';

-- Question 37: Grade 12, Unit bio_g12_u4
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_037', 'biology_g12', 2013, 'new_curriculum_2023', 12, 'bio_g12_u4', 37, 'Population Ecology, Biomes & Environment', 'የህዝብ ብዛት ኢኮሎጂ፣ ባዮሞችና አካባቢ', 'comprehension') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=12, curriculum_unit_id='bio_g12_u4' WHERE id='q_bio_2013_037';

-- Question 38: Grade 12, Unit bio_g12_u4
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_038', 'biology_g12', 2013, 'new_curriculum_2023', 12, 'bio_g12_u4', 38, 'Population Ecology, Biomes & Environment', 'የህዝብ ብዛት ኢኮሎጂ፣ ባዮሞችና አካባቢ', 'analysis') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=12, curriculum_unit_id='bio_g12_u4' WHERE id='q_bio_2013_038';

-- Question 39: Grade 12, Unit bio_g12_u4
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_039', 'biology_g12', 2013, 'new_curriculum_2023', 12, 'bio_g12_u4', 39, 'Population Ecology, Biomes & Environment', 'የህዝብ ብዛት ኢኮሎጂ፣ ባዮሞችና አካባቢ', 'comprehension') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=12, curriculum_unit_id='bio_g12_u4' WHERE id='q_bio_2013_039';

-- Question 40: Grade 12, Unit bio_g12_u4
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_040', 'biology_g12', 2013, 'new_curriculum_2023', 12, 'bio_g12_u4', 40, 'Population Ecology, Biomes & Environment', 'የህዝብ ብዛት ኢኮሎጂ፣ ባዮሞችና አካባቢ', 'application') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=12, curriculum_unit_id='bio_g12_u4' WHERE id='q_bio_2013_040';

-- Question 41: Grade 12, Unit bio_g12_u4
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_041', 'biology_g12', 2013, 'new_curriculum_2023', 12, 'bio_g12_u4', 41, 'Population Ecology, Biomes & Environment', 'የህዝብ ብዛት ኢኮሎጂ፣ ባዮሞችና አካባቢ', 'analysis') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=12, curriculum_unit_id='bio_g12_u4' WHERE id='q_bio_2013_041';

-- Question 42: Grade 12, Unit bio_g12_u4
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_042', 'biology_g12', 2013, 'new_curriculum_2023', 12, 'bio_g12_u4', 42, 'Population Ecology, Biomes & Environment', 'የህዝብ ብዛት ኢኮሎጂ፣ ባዮሞችና አካባቢ', 'analysis') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=12, curriculum_unit_id='bio_g12_u4' WHERE id='q_bio_2013_042';

-- Question 43: Grade 10, Unit bio_g10_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_043', 'biology_g12', 2013, 'new_curriculum_2023', 10, 'bio_g10_u2', 43, 'Heredity and Classical Genetics', 'የዘር ውርስና ክላሲካል ጄኔቲክስ', 'knowledge') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=10, curriculum_unit_id='bio_g10_u2' WHERE id='q_bio_2013_043';

-- Question 44: Grade 10, Unit bio_g10_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_044', 'biology_g12', 2013, 'new_curriculum_2023', 10, 'bio_g10_u2', 44, 'Heredity and Classical Genetics', 'የዘር ውርስና ክላሲካል ጄኔቲክስ', 'application') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=10, curriculum_unit_id='bio_g10_u2' WHERE id='q_bio_2013_044';

-- Question 45: Grade 10, Unit bio_g10_u4
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_045', 'biology_g12', 2013, 'new_curriculum_2023', 10, 'bio_g10_u4', 45, 'Food Production, Agriculture & Breeding', 'የምግብ ምርት፣ ግብርና እና ዝርያ ማሻሻል', 'analysis') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=10, curriculum_unit_id='bio_g10_u4' WHERE id='q_bio_2013_045';

-- Question 46: Grade 12, Unit bio_g12_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_046', 'biology_g12', 2013, 'new_curriculum_2023', 12, 'bio_g12_u2', 46, 'Evolution & Animal Behavior (Ethology)', 'ዝግመተ-ለውጥ እና የእንስሳት ባህሪ', 'comprehension') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=12, curriculum_unit_id='bio_g12_u2' WHERE id='q_bio_2013_046';

-- Question 47: Grade 12, Unit bio_g12_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_047', 'biology_g12', 2013, 'new_curriculum_2023', 12, 'bio_g12_u2', 47, 'Evolution & Animal Behavior (Ethology)', 'ዝግመተ-ለውጥ እና የእንስሳት ባህሪ', 'analysis') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=12, curriculum_unit_id='bio_g12_u2' WHERE id='q_bio_2013_047';

-- Question 48: Grade 12, Unit bio_g12_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_048', 'biology_g12', 2013, 'new_curriculum_2023', 12, 'bio_g12_u2', 48, 'Evolution & Animal Behavior (Ethology)', 'ዝግመተ-ለውጥ እና የእንስሳት ባህሪ', 'knowledge') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=12, curriculum_unit_id='bio_g12_u2' WHERE id='q_bio_2013_048';

-- Question 49: Grade 12, Unit bio_g12_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_049', 'biology_g12', 2013, 'new_curriculum_2023', 12, 'bio_g12_u2', 49, 'Evolution & Animal Behavior (Ethology)', 'ዝግመተ-ለውጥ እና የእንስሳት ባህሪ', 'comprehension') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=12, curriculum_unit_id='bio_g12_u2' WHERE id='q_bio_2013_049';

-- Question 50: Grade 12, Unit bio_g12_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_050', 'biology_g12', 2013, 'new_curriculum_2023', 12, 'bio_g12_u2', 50, 'Evolution & Animal Behavior (Ethology)', 'ዝግመተ-ለውጥ እና የእንስሳት ባህሪ', 'comprehension') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=12, curriculum_unit_id='bio_g12_u2' WHERE id='q_bio_2013_050';

-- Question 51: Grade 11, Unit bio_g11_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_051', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u2', 51, 'Biochemical Molecules & Enzyme Action', 'ባዮኬሚካላዊ ሞለኪዩሎች እና ኢንዛይሞች', 'knowledge') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u2' WHERE id='q_bio_2013_051';

-- Question 52: Grade 11, Unit bio_g11_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_052', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u2', 52, 'Biochemical Molecules & Enzyme Action', 'ባዮኬሚካላዊ ሞለኪዩሎች እና ኢንዛይሞች', 'knowledge') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u2' WHERE id='q_bio_2013_052';

-- Question 53: Grade 11, Unit bio_g11_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_053', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u2', 53, 'Biochemical Molecules & Enzyme Action', 'ባዮኬሚካላዊ ሞለኪዩሎች እና ኢንዛይሞች', 'application') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u2' WHERE id='q_bio_2013_053';

-- Question 54: Grade 11, Unit bio_g11_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_054', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u2', 54, 'Biochemical Molecules & Enzyme Action', 'ባዮኬሚካላዊ ሞለኪዩሎች እና ኢንዛይሞች', 'comprehension') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u2' WHERE id='q_bio_2013_054';

-- Question 55: Grade 11, Unit bio_g11_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_055', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u2', 55, 'Biochemical Molecules & Enzyme Action', 'ባዮኬሚካላዊ ሞለኪዩሎች እና ኢንዛይሞች', 'comprehension') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u2' WHERE id='q_bio_2013_055';

-- Question 56: Grade 9, Unit bio_g9_u1
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_056', 'biology_g12', 2013, 'new_curriculum_2023', 9, 'bio_g9_u1', 56, 'Introduction to Biology & Biological Inquiry', 'የስነ-ህይወት መግቢያ እና ሳይንሳዊ ምርምር', 'comprehension') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=9, curriculum_unit_id='bio_g9_u1' WHERE id='q_bio_2013_056';

-- Question 57: Grade 9, Unit bio_g9_u5
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_057', 'biology_g12', 2013, 'new_curriculum_2023', 9, 'bio_g9_u5', 57, 'Human Health, Nutrition & Infectious Diseases', 'የሰው ጤና፣ አመጋገብ እና ተላላፊ በሽታዎች', 'comprehension') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=9, curriculum_unit_id='bio_g9_u5' WHERE id='q_bio_2013_057';

-- Question 58: Grade 9, Unit bio_g9_u5
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_058', 'biology_g12', 2013, 'new_curriculum_2023', 9, 'bio_g9_u5', 58, 'Human Health, Nutrition & Infectious Diseases', 'የሰው ጤና፣ አመጋገብ እና ተላላፊ በሽታዎች', 'knowledge') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=9, curriculum_unit_id='bio_g9_u5' WHERE id='q_bio_2013_058';

-- Question 59: Grade 11, Unit bio_g11_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_059', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u2', 59, 'Biochemical Molecules & Enzyme Action', 'ባዮኬሚካላዊ ሞለኪዩሎች እና ኢንዛይሞች', 'comprehension') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u2' WHERE id='q_bio_2013_059';

-- Question 60: Grade 9, Unit bio_g9_u5
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_060', 'biology_g12', 2013, 'new_curriculum_2023', 9, 'bio_g9_u5', 60, 'Human Health, Nutrition & Infectious Diseases', 'የሰው ጤና፣ አመጋገብ እና ተላላፊ በሽታዎች', 'application') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=9, curriculum_unit_id='bio_g9_u5' WHERE id='q_bio_2013_060';

-- Question 61: Grade 11, Unit bio_g11_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_061', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u2', 61, 'Biochemical Molecules & Enzyme Action', 'ባዮኬሚካላዊ ሞለኪዩሎች እና ኢንዛይሞች', 'application') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u2' WHERE id='q_bio_2013_061';

-- Question 62: Grade 11, Unit bio_g11_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_062', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u2', 62, 'Biochemical Molecules & Enzyme Action', 'ባዮኬሚካላዊ ሞለኪዩሎች እና ኢንዛይሞች', 'analysis') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u2' WHERE id='q_bio_2013_062';

-- Question 63: Grade 11, Unit bio_g11_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_063', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u2', 63, 'Biochemical Molecules & Enzyme Action', 'ባዮኬሚካላዊ ሞለኪዩሎች እና ኢንዛይሞች', 'knowledge') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u2' WHERE id='q_bio_2013_063';

-- Question 64: Grade 11, Unit bio_g11_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_064', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u2', 64, 'Biochemical Molecules & Enzyme Action', 'ባዮኬሚካላዊ ሞለኪዩሎች እና ኢንዛይሞች', 'comprehension') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u2' WHERE id='q_bio_2013_064';

-- Question 65: Grade 11, Unit bio_g11_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_065', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u2', 65, 'Biochemical Molecules & Enzyme Action', 'ባዮኬሚካላዊ ሞለኪዩሎች እና ኢንዛይሞች', 'knowledge') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u2' WHERE id='q_bio_2013_065';

-- Question 66: Grade 11, Unit bio_g11_u3
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_066', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u3', 66, 'Cellular Transport & Membrane Dynamics', 'የሴል ሽፋን ዝውውር', 'analysis') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u3' WHERE id='q_bio_2013_066';

-- Question 67: Grade 11, Unit bio_g11_u3
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_067', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u3', 67, 'Cellular Transport & Membrane Dynamics', 'የሴል ሽፋን ዝውውር', 'application') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u3' WHERE id='q_bio_2013_067';

-- Question 68: Grade 11, Unit bio_g11_u3
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_068', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u3', 68, 'Cellular Transport & Membrane Dynamics', 'የሴል ሽፋን ዝውውር', 'comprehension') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u3' WHERE id='q_bio_2013_068';

-- Question 69: Grade 11, Unit bio_g11_u3
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_069', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u3', 69, 'Cellular Transport & Membrane Dynamics', 'የሴል ሽፋን ዝውውር', 'analysis') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u3' WHERE id='q_bio_2013_069';

-- Question 70: Grade 10, Unit bio_g10_u3
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_070', 'biology_g12', 2013, 'new_curriculum_2023', 10, 'bio_g10_u3', 70, 'Human Biology: Body Systems', 'የሰው አካል ስርዓቶች', 'application') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=10, curriculum_unit_id='bio_g10_u3' WHERE id='q_bio_2013_070';

-- Question 71: Grade 9, Unit bio_g9_u3
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_071', 'biology_g12', 2013, 'new_curriculum_2023', 9, 'bio_g9_u3', 71, 'Cell Biology & Structure', 'የሴል ስነ-ህይወትና መዋቅር', 'knowledge') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=9, curriculum_unit_id='bio_g9_u3' WHERE id='q_bio_2013_071';

-- Question 72: Grade 9, Unit bio_g9_u3
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_072', 'biology_g12', 2013, 'new_curriculum_2023', 9, 'bio_g9_u3', 72, 'Cell Biology & Structure', 'የሴል ስነ-ህይወትና መዋቅር', 'analysis') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=9, curriculum_unit_id='bio_g9_u3' WHERE id='q_bio_2013_072';

-- Question 73: Grade 9, Unit bio_g9_u3
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_073', 'biology_g12', 2013, 'new_curriculum_2023', 9, 'bio_g9_u3', 73, 'Cell Biology & Structure', 'የሴል ስነ-ህይወትና መዋቅር', 'analysis') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=9, curriculum_unit_id='bio_g9_u3' WHERE id='q_bio_2013_073';

-- Question 74: Grade 11, Unit bio_g11_u3
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_074', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u3', 74, 'Cellular Transport & Membrane Dynamics', 'የሴል ሽፋን ዝውውር', 'comprehension') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u3' WHERE id='q_bio_2013_074';

-- Question 75: Grade 9, Unit bio_g9_u3
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_075', 'biology_g12', 2013, 'new_curriculum_2023', 9, 'bio_g9_u3', 75, 'Cell Biology & Structure', 'የሴል ስነ-ህይወትና መዋቅር', 'comprehension') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=9, curriculum_unit_id='bio_g9_u3' WHERE id='q_bio_2013_075';

-- Question 76: Grade 11, Unit bio_g11_u4
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_076', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u4', 76, 'Energy Transformation: Photosynthesis & Respiration', 'የሃይል ልውውጥ፡ ፎቶሲንተሲስና ሴሉላር አተነፋፈስ', 'comprehension') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u4' WHERE id='q_bio_2013_076';

-- Question 77: Grade 11, Unit bio_g11_u4
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_077', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u4', 77, 'Energy Transformation: Photosynthesis & Respiration', 'የሃይል ልውውጥ፡ ፎቶሲንተሲስና ሴሉላር አተነፋፈስ', 'analysis') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u4' WHERE id='q_bio_2013_077';

-- Question 78: Grade 11, Unit bio_g11_u4
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_078', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u4', 78, 'Energy Transformation: Photosynthesis & Respiration', 'የሃይል ልውውጥ፡ ፎቶሲንተሲስና ሴሉላር አተነፋፈስ', 'application') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u4' WHERE id='q_bio_2013_078';

-- Question 79: Grade 11, Unit bio_g11_u4
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_079', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u4', 79, 'Energy Transformation: Photosynthesis & Respiration', 'የሃይል ልውውጥ፡ ፎቶሲንተሲስና ሴሉላር አተነፋፈስ', 'comprehension') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u4' WHERE id='q_bio_2013_079';

-- Question 80: Grade 11, Unit bio_g11_u4
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_080', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u4', 80, 'Energy Transformation: Photosynthesis & Respiration', 'የሃይል ልውውጥ፡ ፎቶሲንተሲስና ሴሉላር አተነፋፈስ', 'comprehension') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u4' WHERE id='q_bio_2013_080';

-- Question 81: Grade 11, Unit bio_g11_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_081', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u2', 81, 'Biochemical Molecules & Enzyme Action', 'ባዮኬሚካላዊ ሞለኪዩሎች እና ኢንዛይሞች', 'comprehension') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u2' WHERE id='q_bio_2013_081';

-- Question 82: Grade 11, Unit bio_g11_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_082', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u2', 82, 'Biochemical Molecules & Enzyme Action', 'ባዮኬሚካላዊ ሞለኪዩሎች እና ኢንዛይሞች', 'analysis') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u2' WHERE id='q_bio_2013_082';

-- Question 83: Grade 11, Unit bio_g11_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_083', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u2', 83, 'Biochemical Molecules & Enzyme Action', 'ባዮኬሚካላዊ ሞለኪዩሎች እና ኢንዛይሞች', 'knowledge') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u2' WHERE id='q_bio_2013_083';

-- Question 84: Grade 11, Unit bio_g11_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_084', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u2', 84, 'Biochemical Molecules & Enzyme Action', 'ባዮኬሚካላዊ ሞለኪዩሎች እና ኢንዛይሞች', 'comprehension') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u2' WHERE id='q_bio_2013_084';

-- Question 85: Grade 11, Unit bio_g11_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_085', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u2', 85, 'Biochemical Molecules & Enzyme Action', 'ባዮኬሚካላዊ ሞለኪዩሎች እና ኢንዛይሞች', 'knowledge') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u2' WHERE id='q_bio_2013_085';

-- Question 86: Grade 10, Unit bio_g10_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_086', 'biology_g12', 2013, 'new_curriculum_2023', 10, 'bio_g10_u2', 86, 'Heredity and Classical Genetics', 'የዘር ውርስና ክላሲካል ጄኔቲክስ', 'comprehension') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=10, curriculum_unit_id='bio_g10_u2' WHERE id='q_bio_2013_086';

-- Question 87: Grade 11, Unit bio_g11_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_087', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u2', 87, 'Biochemical Molecules & Enzyme Action', 'ባዮኬሚካላዊ ሞለኪዩሎች እና ኢንዛይሞች', 'comprehension') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u2' WHERE id='q_bio_2013_087';

-- Question 88: Grade 12, Unit bio_g12_u3
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_088', 'biology_g12', 2013, 'new_curriculum_2023', 12, 'bio_g12_u3', 88, 'Applied Biotechnology & Genetic Engineering', 'የተግባራዊ ባዮቴክኖሎጂና ጄኔቲክ ምህንድስና', 'analysis') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=12, curriculum_unit_id='bio_g12_u3' WHERE id='q_bio_2013_088';

-- Question 89: Grade 11, Unit bio_g11_u5
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_089', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u5', 89, 'Molecular Genetics & Protein Synthesis', 'ሞለኪዩላር ጄኔቲክስ እና የፕሮቲን ቅንብር', 'application') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u5' WHERE id='q_bio_2013_089';

-- Question 90: Grade 11, Unit bio_g11_u5
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_090', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u5', 90, 'Molecular Genetics & Protein Synthesis', 'ሞለኪዩላር ጄኔቲክስ እና የፕሮቲን ቅንብር', 'comprehension') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u5' WHERE id='q_bio_2013_090';

-- Question 91: Grade 11, Unit bio_g11_u1
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_091', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u1', 91, 'Biological Research, Methodology & Tools', 'የስነ-ህይወት ምርምር፣ ዘዴዎችና መሳሪያዎች', 'knowledge') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u1' WHERE id='q_bio_2013_091';

-- Question 92: Grade 11, Unit bio_g11_u1
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_092', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u1', 92, 'Biological Research, Methodology & Tools', 'የስነ-ህይወት ምርምር፣ ዘዴዎችና መሳሪያዎች', 'application') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u1' WHERE id='q_bio_2013_092';

-- Question 93: Grade 11, Unit bio_g11_u1
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_093', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u1', 93, 'Biological Research, Methodology & Tools', 'የስነ-ህይወት ምርምር፣ ዘዴዎችና መሳሪያዎች', 'analysis') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u1' WHERE id='q_bio_2013_093';

-- Question 94: Grade 11, Unit bio_g11_u1
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_094', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u1', 94, 'Biological Research, Methodology & Tools', 'የስነ-ህይወት ምርምር፣ ዘዴዎችና መሳሪያዎች', 'comprehension') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u1' WHERE id='q_bio_2013_094';

-- Question 95: Grade 11, Unit bio_g11_u1
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_095', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u1', 95, 'Biological Research, Methodology & Tools', 'የስነ-ህይወት ምርምር፣ ዘዴዎችና መሳሪያዎች', 'application') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u1' WHERE id='q_bio_2013_095';

-- Question 96: Grade 11, Unit bio_g11_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_096', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u2', 96, 'Biochemical Molecules & Enzyme Action', 'ባዮኬሚካላዊ ሞለኪዩሎች እና ኢንዛይሞች', 'comprehension') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u2' WHERE id='q_bio_2013_096';

-- Question 97: Grade 11, Unit bio_g11_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_097', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u2', 97, 'Biochemical Molecules & Enzyme Action', 'ባዮኬሚካላዊ ሞለኪዩሎች እና ኢንዛይሞች', 'analysis') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u2' WHERE id='q_bio_2013_097';

-- Question 98: Grade 11, Unit bio_g11_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_098', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u2', 98, 'Biochemical Molecules & Enzyme Action', 'ባዮኬሚካላዊ ሞለኪዩሎች እና ኢንዛይሞች', 'comprehension') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u2' WHERE id='q_bio_2013_098';

-- Question 99: Grade 11, Unit bio_g11_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_099', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u2', 99, 'Biochemical Molecules & Enzyme Action', 'ባዮኬሚካላዊ ሞለኪዩሎች እና ኢንዛይሞች', 'application') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u2' WHERE id='q_bio_2013_099';

-- Question 100: Grade 11, Unit bio_g11_u2
INSERT INTO public.question_curriculum_mappings (question_id, subject_id, exam_year, curriculum_framework, curriculum_grade, curriculum_unit_id, question_order_in_exam, unit_title_en, unit_title_am, cognitive_level) VALUES ('q_bio_2013_100', 'biology_g12', 2013, 'new_curriculum_2023', 11, 'bio_g11_u2', 100, 'Biochemical Molecules & Enzyme Action', 'ባዮኬሚካላዊ ሞለኪዩሎች እና ኢንዛይሞች', 'application') ON CONFLICT (question_id, curriculum_framework) DO UPDATE SET curriculum_grade=EXCLUDED.curriculum_grade, curriculum_unit_id=EXCLUDED.curriculum_unit_id, unit_title_en=EXCLUDED.unit_title_en, unit_title_am=EXCLUDED.unit_title_am, cognitive_level=EXCLUDED.cognitive_level;
UPDATE public.questions SET curriculum_framework='new_curriculum_2023', curriculum_grade=11, curriculum_unit_id='bio_g11_u2' WHERE id='q_bio_2013_100';
